version: '3.6'

services:
  web:
    build: .
    container_name: PruebaWeb
    volumes:
      - ./src:/var/www/html
    
    ports:
      - "9090:80"
    restart: always
  db:
    image: mysql:5.7
    container_name: PrensaMichoacanaDB
    restart: always
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - MYSQL_ROOT_PASSWORD=qwerty12345
      - MYSQL_USER=administrator
      - MYSQL_PASSWORD=adminpass123
      - MYSQL_DATABASE=PrensaMichoacana
    ports:
      - "3308:3306"
networks:
 default:
  external:
   name: docker_development  