version: '3.6'

services:
  web:
    build: .
    #image: php:7.1-apache
    container_name: PruebaWeb
    volumes:
      - ./src:/var/www/html
    
    ports:
      - "9090:80"
    restart: always
  
networks:
 default:
  external:
   name: docker_development  